# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Poetry
      run: |
        sudo apt-get update
        sudo apt-get install curl -y
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        echo $PATH
        ::add-path::$HOME/.poetry/bin
        echo $PATH
    - name: Env Check
      run: |
        env
        echo ${PATH}
#    - name: Install dependencies
#      env:
#        PATH:
#      run: |
#        ls -la $HOME
#        env
#        poetry install --no-dev
#    - name: Install dependencies
#      run: |
#        poetry install --no-dev
#    - name: Python
#      env:
#        HELLO_WORLD: ${{ secrets.hello_world }}
#      run: |
#        python --version
